### ISSUE TITLE
Have an error

### ISSUE THREAD

**Issue by asc123q** [WincerChan/SolVanityCL#11]
Hi. I recieve this error.
Using on windows.

PS D:\SolVanityCL> python main.py search-pubkey --starts-with SoL
[INFO 2024-06-24 00:25:51,328] Searching Solana pubkey that starts with 'SoL' and ends with ''
[INFO 2024-06-24 00:25:53,790] Searching with 2 OpenCL devices
1 warning and 273 errors generated.
[ERROR 2024-06-24 00:25:54,257] clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce RTX 3060 Laptop GPU' on 'NVIDIA CUDA' at 0x1965f3d2480>:

<kernel>:3134:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_add(r->X, p->Y, p->X);
         ^~~~
<kernel>:2982:26: note: passing argument to parameter 'h' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3134:16: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(r->X, p->Y, p->X);
               ^~~~
<kernel>:2982:48: note: passing argument to parameter 'f' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:3134:22: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(r->X, p->Y, p->X);
                     ^~~~
<kernel>:2982:70: note: passing argument to parameter 'g' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3135:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_sub(r->Y, p->Y, p->X);
         ^~~~
<kernel>:2938:26: note: passing argument to parameter 'h' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3135:16: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_sub(r->Y, p->Y, p->X);
               ^~~~
<kernel>:2938:48: note: passing argument to parameter 'f' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:3135:22: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_sub(r->Y, p->Y, p->X);
                     ^~~~
<kernel>:2938:70: note: passing argument to parameter 'g' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3136:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_mul(r->Z, r->X, q->YplusX);
         ^~~~
<kernel>:2717:26: note: passing argument to parameter 'h' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3136:16: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(r->Z, r->X, q->YplusX);
               ^~~~
<kernel>:2717:48: note: passing argument to parameter 'f' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:3136:22: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(r->Z, r->X, q->YplusX);
                     ^~~~~~~~~
<kernel>:2717:70: note: passing argument to parameter 'g' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3137:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_mul(r->Y, r->Y, q->YminusX);
         ^~~~
<kernel>:2717:26: note: passing argument to parameter 'h' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3137:16: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(r->Y, r->Y, q->YminusX);
               ^~~~
<kernel>:2717:48: note: passing argument to parameter 'f' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:3137:22: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(r->Y, r->Y, q->YminusX);
                     ^~~~~~~~~~
<kernel>:2717:70: note: passing argument to parameter 'g' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3138:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_mul(r->T, q->T2d, p->T);
         ^~~~
<kernel>:2717:26: note: passing argument to parameter 'h' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3138:16: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(r->T, q->T2d, p->T);
               ^~~~~~
<kernel>:2717:48: note: passing argument to parameter 'f' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:3138:24: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(r->T, q->T2d, p->T);
                       ^~~~
<kernel>:2717:70: note: passing argument to parameter 'g' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3139:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_mul(r->X, p->Z, q->Z);
         ^~~~
<kernel>:2717:26: note: passing argument to parameter 'h' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3139:16: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(r->X, p->Z, q->Z);
               ^~~~
<kernel>:2717:48: note: passing argument to parameter 'f' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:3139:22: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(r->X, p->Z, q->Z);
                     ^~~~
<kernel>:2717:70: note: passing argument to parameter 'g' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3140:14: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(t0, r->X, r->X);
             ^~~~
<kernel>:2982:48: note: passing argument to parameter 'f' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:3140:20: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(t0, r->X, r->X);
                   ^~~~
<kernel>:2982:70: note: passing argument to parameter 'g' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3141:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_sub(r->X, r->Z, r->Y);
         ^~~~
<kernel>:2938:26: note: passing argument to parameter 'h' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3141:16: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_sub(r->X, r->Z, r->Y);
               ^~~~
<kernel>:2938:48: note: passing argument to parameter 'f' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:3141:22: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_sub(r->X, r->Z, r->Y);
                     ^~~~
<kernel>:2938:70: note: passing argument to parameter 'g' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3142:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_add(r->Y, r->Z, r->Y);
         ^~~~
<kernel>:2982:26: note: passing argument to parameter 'h' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3142:16: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(r->Y, r->Z, r->Y);
               ^~~~
<kernel>:2982:48: note: passing argument to parameter 'f' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:3142:22: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(r->Y, r->Z, r->Y);
                     ^~~~
<kernel>:2982:70: note: passing argument to parameter 'g' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3143:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_add(r->Z, t0, r->T);
         ^~~~
<kernel>:2982:26: note: passing argument to parameter 'h' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3143:20: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(r->Z, t0, r->T);
                   ^~~~
<kernel>:2982:70: note: passing argument to parameter 'g' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:3144:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_sub(r->T, t0, r->T);
         ^~~~
<kernel>:2938:26: note: passing argument to parameter 'h' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:3144:20: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_sub(r->T, t0, r->T);
                   ^~~~
<kernel>:2938:70: note: passing argument to parameter 'g' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:4276:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_add(r->YplusX, p->Y, p->X);
         ^~~~~~~~~
<kernel>:2982:26: note: passing argument to parameter 'h' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:4276:21: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(r->YplusX, p->Y, p->X);
                    ^~~~
<kernel>:2982:48: note: passing argument to parameter 'f' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:4276:27: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(r->YplusX, p->Y, p->X);
                          ^~~~
<kernel>:2982:70: note: passing argument to parameter 'g' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:4277:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_sub(r->YminusX, p->Y, p->X);
         ^~~~~~~~~~
<kernel>:2938:26: note: passing argument to parameter 'h' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:4277:22: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_sub(r->YminusX, p->Y, p->X);
                     ^~~~
<kernel>:2938:48: note: passing argument to parameter 'f' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:4277:28: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_sub(r->YminusX, p->Y, p->X);
                           ^~~~
<kernel>:2938:70: note: passing argument to parameter 'g' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:4278:11: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_copy(r->Z, p->Z);
          ^~~~
<kernel>:3512:27: note: passing argument to parameter 'h' here
void fe_copy(__generic fe h, const __generic fe f) {
                          ^
<kernel>:4278:17: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_copy(r->Z, p->Z);
                ^~~~
<kernel>:3512:49: note: passing argument to parameter 'f' here
void fe_copy(__generic fe h, const __generic fe f) {
                                                ^
<kernel>:4279:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_mul(r->T2d, p->T, d2);
         ^~~~~~
<kernel>:2717:26: note: passing argument to parameter 'h' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:4279:18: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(r->T2d, p->T, d2);
                 ^~~~
<kernel>:2717:48: note: passing argument to parameter 'f' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:4287:11: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_copy(r->X, p->X);
          ^~~~
<kernel>:3512:27: note: passing argument to parameter 'h' here
void fe_copy(__generic fe h, const __generic fe f) {
                          ^
<kernel>:4287:17: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_copy(r->X, p->X);
                ^~~~
<kernel>:3512:49: note: passing argument to parameter 'f' here
void fe_copy(__generic fe h, const __generic fe f) {
                                                ^
<kernel>:4288:11: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_copy(r->Y, p->Y);
          ^~~~
<kernel>:3512:27: note: passing argument to parameter 'h' here
void fe_copy(__generic fe h, const __generic fe f) {
                          ^
<kernel>:4288:17: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_copy(r->Y, p->Y);
                ^~~~
<kernel>:3512:49: note: passing argument to parameter 'f' here
void fe_copy(__generic fe h, const __generic fe f) {
                                                ^
<kernel>:4289:11: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_copy(r->Z, p->Z);
          ^~~~
<kernel>:3512:27: note: passing argument to parameter 'h' here
void fe_copy(__generic fe h, const __generic fe f) {
                          ^
<kernel>:4289:17: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_copy(r->Z, p->Z);
                ^~~~
<kernel>:3512:49: note: passing argument to parameter 'f' here
void fe_copy(__generic fe h, const __generic fe f) {
                                                ^
<kernel>:4296:20: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_invert(recip, h->Z);
                   ^~~~
<kernel>:3605:53: note: passing argument to parameter 'z' here
void fe_invert(__generic fe out, const __generic fe z) {
                                                    ^
<kernel>:4297:13: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(x, h->X, recip);
            ^~~~
<kernel>:2717:48: note: passing argument to parameter 'f' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:4298:13: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul(y, h->Y, recip);
            ^~~~
<kernel>:2717:48: note: passing argument to parameter 'f' here
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:4305:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_add(r->X, p->Y, p->X);
         ^~~~
<kernel>:2982:26: note: passing argument to parameter 'h' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:4305:16: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(r->X, p->Y, p->X);
               ^~~~
<kernel>:2982:48: note: passing argument to parameter 'f' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:4305:22: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_add(r->X, p->Y, p->X);
                     ^~~~
<kernel>:2982:70: note: passing argument to parameter 'g' here
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:4306:10: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_sub(r->Y, p->Y, p->X);
         ^~~~
<kernel>:2938:26: note: passing argument to parameter 'h' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                         ^
<kernel>:4306:16: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_sub(r->Y, p->Y, p->X);
               ^~~~
<kernel>:2938:48: note: passing argument to parameter 'f' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                               ^
<kernel>:4306:22: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_sub(r->Y, p->Y, p->X);
                     ^~~~
<kernel>:2938:70: note: passing argument to parameter 'g' here
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                                                     ^
<kernel>:4307:20: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_mul__contant2(r->Z, r->X, q->yplusx);
                   ^~~~
<kernel>:2276:36: note: passing argument to parameter 'h' here
void fe_mul__contant2(__generic fe h, const __generic fe f, constant fe g) {
                                   ^
<kernel>:4307:26: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul__contant2(r->Z, r->X, q->yplusx);
                         ^~~~
<kernel>:2276:58: note: passing argument to parameter 'f' here
void fe_mul__contant2(__generic fe h, const __generic fe f, constant fe g) {
                                                         ^
<kernel>:4308:20: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_mul__contant2(r->Y, r->Y, q->yminusx);
                   ^~~~
<kernel>:2276:36: note: passing argument to parameter 'h' here
void fe_mul__contant2(__generic fe h, const __generic fe f, constant fe g) {
                                   ^
<kernel>:4308:26: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul__contant2(r->Y, r->Y, q->yminusx);
                         ^~~~
<kernel>:2276:58: note: passing argument to parameter 'f' here
void fe_mul__contant2(__generic fe h, const __generic fe f, constant fe g) {
                                                         ^
<kernel>:4309:20: error: passing '__generic int32_t *' (aka '__generic int *') to parameter of type 'int32_t *' (aka 'int *') changes address space of pointer
  fe_mul__contant1(r->T, q->xy2d, p->T);
                   ^~~~
<kernel>:2496:36: note: passing argument to parameter 'h' here
void fe_mul__contant1(__generic fe h, constant fe f, const __generic fe g) {
                                   ^
<kernel>:4309:35: error: passing 'const __generic int32_t *' (aka 'const __generic int *') to parameter of type 'const int32_t *' (aka 'const int *') changes address space of pointer
  fe_mul__contant1(r->T, q->xy2d, p->T);
                                  ^~~~
         
         
(......)

(options: -I C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\cl)
InvalidArraySize: Array size must be at least 1: [0 x i8] [Src: d:\qb\workspace\22235\source\llvm_source\llvm\projects\llvm-spirv\lib\spirv\spirvwriter.cpp:366 T->getArrayNumElements() >= 1 ]

**Comment by WincerChan** [comment]
Hello, I don’t have a Windows + Nvidia device. Addressing these errors might require testing. Can you run this code and paste the output?
```
import pyopencl as cl
import platform
print(cl.get_cl_header_version())
print(platform.system())
```

**Comment by asc123q** [comment]
PS D:\SolVanityCL> python main2.py
(3, 0)
Windows

**Comment by asc123q** [comment]
Also I recieve different errors when use device select, like cuda gives me errors I started the thread, but when others : 

PS D:\SolVanityCL> python main.py search-pubkey --starts-with SoL --select-device
[INFO 2024-06-24 11:50:47,998] Searching Solana pubkey that starts with 'SoL' and ends with ''
[INFO 2024-06-24 11:50:49,137] Searching with 2 OpenCL devices
Choose platform:
[0] <pyopencl.Platform 'NVIDIA CUDA' at 0x2237034f540>
[1] <pyopencl.Platform 'Intel(R) OpenCL HD Graphics' at 0x22370358900>
[2] <pyopencl.Platform 'Intel(R) OpenCL' at 0x223779a9d98>
Choice [0]:1
Set the environment variable PYOPENCL_CTX='1' to avoid being asked again.
InvalidArraySize: Array size must be at least 1: [0 x i8] [Src: d:\qb\workspace\22235\source\llvm_source\llvm\projects\llvm-spirv\lib\spirv\spirvwriter.cpp:366 T->getArrayNumElements() >= 1 ]

==================================================================================================================================
PS D:\SolVanityCL>
PS D:\SolVanityCL> python main.py search-pubkey --starts-with SoL --select-device
[INFO 2024-06-24 11:51:20,108] Searching Solana pubkey that starts with 'SoL' and ends with ''
[INFO 2024-06-24 11:51:21,303] Searching with 2 OpenCL devices
Choose platform:
[0] <pyopencl.Platform 'NVIDIA CUDA' at 0x234dbb8ba40>
[1] <pyopencl.Platform 'Intel(R) OpenCL HD Graphics' at 0x234dbc33350>
[2] <pyopencl.Platform 'Intel(R) OpenCL' at 0x234e32e2a88>
Choice [0]:2
Set the environment variable PYOPENCL_CTX='2' to avoid being asked again.
C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\__init__.py:527: UserWarning: PyOpenCL compiler caching failed with an exception:
[begin exception]
Traceback (most recent call last):
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\cache.py", line 495, in create_built_program_from_source_cached
    _create_built_program_from_source_cached(
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\cache.py", line 417, in _create_built_program_from_source_cached
    prg.build(options_bytes, [devices[i] for i in to_be_built_indices])
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\__init__.py", line 746, in program_build
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: OUT_OF_RESOURCES - clBuildProgram failed: OUT_OF_RESOURCES

Build on <pyopencl.Device '12th Gen Intel(R) Core(TM) i5-12450H' on 'Intel(R) OpenCL' at 0x234dbb85a80>:

Compilation started
1:5051:9: warning: type specifier missing, defaults to 'int'
  const global_id = (*group_offset) * get_global_size(0) + get_global_id(0);
  ~~~~~ ^
Compilation done
Linking started
Linking done
Device build started
Options used by backend compiler: -I C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\cl
Device build done
Kernel <generate_pubkey> was successfully vectorized (8)
Done.
[end exception]
  lambda: create_built_program_from_source_cached(
Traceback (most recent call last):
  File "D:\SolVanityCL\main.py", line 325, in <module>
    cli()
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SolVanityCL\main.py", line 287, in search_pubkey
    searcher = Searcher(
               ^^^^^^^^^
  File "D:\SolVanityCL\main.py", line 157, in __init__
    program = cl.Program(self.context, kernel_source).build()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\__init__.py", line 526, in build
    self._prg, was_cached = self._build_and_catch_errors(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\__init__.py", line 574, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: OUT_OF_RESOURCES - clBuildProgram failed: OUT_OF_RESOURCES - clBuildProgram failed: OUT_OF_RESOURCES

Build on <pyopencl.Device '12th Gen Intel(R) Core(TM) i5-12450H' on 'Intel(R) OpenCL' at 0x234dbb85a80>:

Compilation started
2:5051:9: warning: type specifier missing, defaults to 'int'
  const global_id = (*group_offset) * get_global_size(0) + get_global_id(0);
  ~~~~~ ^
Compilation done
Linking started
Linking done
Device build started
Options used by backend compiler: -I C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\cl
Device build done
Kernel <generate_pubkey> was successfully vectorized (8)
Done.
(options: -I C:\Users\ctrad\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\cl)
(source saved as C:\Users\ctrad\AppData\Local\Temp\tmpnaxccjyk.cl)

**Comment by WincerChan** [comment]
Only Nvidia, AMD, and Apple GPU devices are supported. Intel GPUs are not supported. Your device has multiple GPUs, so the –select-device parameter is mandatory, you should always select option 0.
Additionally, I am not sure of the reason for the compile error you encountered. Maybe you can try deleting the first line in the `opencl/kernel.cl` file: ~~#define __generic~~, and then re-run the command.

**Comment by asc123q** [comment]
Can you give me your telegram? I have an offer for you

**Comment by WincerChan** [comment]
@asc123q This is my telegram: https://t.me/Tivsae

**Comment by WincerChan** [comment]
fixed https://github.com/WincerChan/SolVanityCL/pull/12
