### ISSUE TITLE
Ubuntu 20.04 + RTX 4090 (rented container) - Unlucky or bug?

### ISSUE THREAD

**Issue by Sayrix** [WincerChan/SolVanityCL#6]
Hi, i've rented a docker container with Ubuntu 20.04 and a RTX 4090 and it works pretty well! 66 MH/s is HUGE but, i think that it's useless with what i want. I tried for more than 20 minutes to find an address that starts with 6 letter, so 58<sup>6</sup> and at 66 MH/s it should take about 576 seconds so ~11 minutes. So after 20 minutes i where thinking if it's me that is unlucky or a bug. So what i did is trying with 5 letters which should take about 9 seconds, but after easily 1 minute nothing found. I tried with 4 letters and it found it instantly, is it me that is unlucky or a bug ?

**Comment by Sayrix** [comment]
By the way, i've rented multiple instances to try multiple GPU hashrate, here is my result:
| GPU | Hashrate |
|--------|--------|
| RTX 3080 | 23 MH/s |
| RTX 3090 | 27 MH/s | 
| RTX 3080 Ti | 28 MH/s | 
| RTX 4070 Ti | 31 MH/s | 
| RTX 4090 | 66 MH/s |

**Comment by WincerChan** [comment]
Actually, the number of attempts required to find a Solana address with a specific 6-letter prefix is not simply 58^6. Solana uses ed25519 for private and public key generation. 

In ed25519, all inputs are processed by a SHA-512 operation, which introduces high randomness. This causes the input to the elliptic curve to be discontinuous, making the output discontinuous as well.

**Comment by Sayrix** [comment]
Oh okay, i will try to run it for 2 hours @ 23 MH/s i don't know if it will be enough

**Comment by Sayrix** [comment]
Okay so 2 hours later still nothing found. I don't know if it's me that is unlucky or if it's a bug 😔

**Comment by Sayrix** [comment]
Hi i think there is a CPU bottleneck because the program is single threaded and uses 100% of 1 core, so here is a feature request: multithread the program maybe it will make the program more faster

**Comment by WincerChan** [comment]
> Okay so 2 hours later still nothing found. I don't know if it's me that is unlucky or if it's a bug 😔
<img width="545" alt="screenshot" src="https://github.com/WincerChan/SolVanityCL/assets/16951341/c4fec674-fd60-4c04-ab29-0d8f19d44d63">

I ran it for 2 hours at 30 MH/s and it found an address with a 6-letter prefix.

**Comment by WincerChan** [comment]
> Hi i think there is a CPU bottleneck because the program is single threaded and uses 100% of 1 core, so here is a feature request: multithread the program maybe it will make the program more faster

Actually, this is a known issue when running OpenCL on Nvidia GPUs. You can check the details here: https://github.com/openwall/john/issues/4781.
However, if you use an AMD GPU or an ARM64 Darwin system, the CPU usage is fine. The CPU will not be a bottleneck here.

**Comment by Sayrix** [comment]
Oh ok, so there is no solution to it, you can't multi-thread the task ? And by the way, i found 2x 6 letter address but after easily 5-6 hours at 66 MH/s

**Comment by WincerChan** [comment]
> Oh ok, so there is no solution to it, you can't multi-thread the task ? And by the way, i found 2x 6 letter address but after easily 5-6 hours at 66 MH/s

I am planning to add support for multiple GPUs. Only in multi-GPU setups does supporting CPU multiprocessing make sense, because in the case of Nvidia GPUs, each GPU fully utilizes one CPU core.
