### ISSUE TITLE
Error : 'TypeError("cannot pickle '_ErrorRecord' object")'

### ISSUE THREAD

**Issue by wngasinur** [WincerChan/SolVanityCL#8]
I've rented GPU RTX 4090 in runpod, getting following issue

python main.py search-pubkey --starts-with sol
[INFO 2024-06-05 13:23:10,499] Searching Solana pubkey that starts with 'sol' and ends with ''
Traceback (most recent call last):
  File "/SolVanityCL/main.py", line 326, in <module>
    cli()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/SolVanityCL/main.py", line 279, in search_pubkey
    gpu_counts = len(pool.apply(get_all_gpu_devices))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 360, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7fc197c165f0>'. Reason: 'TypeError("cannot pickle '_ErrorRecord' object")'

Any idea ?

**Comment by WincerChan** [comment]
hello, please add --select-device parameter, and paste the output.
`python main.py search-pubkey --starts-with sol --select-device`

**Comment by wngasinur** [comment]
root@39d813894983:/SolVanityCL# python main.py search-pubkey --select-device --starts-with So
[INFO 2024-06-06 12:32:36,226] Searching Solana pubkey that starts with 'So' and ends with ''
Traceback (most recent call last):
  File "/SolVanityCL/main.py", line 326, in <module>
    cli()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/SolVanityCL/main.py", line 279, in search_pubkey
    gpu_counts = len(pool.apply(get_all_gpu_devices))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 360, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7fe9716865f0>'. Reason: 'TypeError("cannot pickle '_ErrorRecord' object")'

same issue

**Comment by WincerChan** [comment]
I tend to think this is an Nvidia driver issue. I rented a GPU device this afternoon and did not encounter the same problem as you. You can try installing clinfo (sudo apt-get install -y clinfo) and print the driver version.

**Comment by wngasinur** [comment]
root@d5996bb3e2b2:/SolVanityCL# clinfo
Number of platforms                               0

root@d5996bb3e2b2:/SolVanityCL# nvidia-smi
Thu Jun  6 13:31:56 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A40                     On  | 00000000:56:00.0 Off |                    0 |
|  0%   32C    P8              21W / 300W |      0MiB / 46068MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+


Which rented GPU platform did you use ? I use runpod 
1 x A40
9 vCPU 50 GB RAM
runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04

**Comment by WincerChan** [comment]
root@d5996bb3e2b2:/SolVanityCL# clinfo
Number of platforms 0
The output of this command indicates the issue. Your device does not have the OpenCL driver installed.
I think the point is the Docker image. You can try this [nvidia/opencl](https://hub.docker.com/r/nvidia/opencl/)
image. I haven't used runpod before; I use vast.ai, but the platform should be alright.

**Comment by wngasinur** [comment]
Thanks let me close the issue, I will play around with some other docker images

**Comment by wngasinur** [comment]
Btw I just checked from NVIDIA website, it said R465 and above is automatically support OpenCL 3.0. 

"NVIDIA is now OpenCL 3.0 conformant and is available on R465 and later drivers. This is supported on x86/x86_64 Linux and Windows only and available at [www.nvidia.com/drivers](https://www.nvidia.com/drivers)" 
https://developer.nvidia.com/opencl

Can you share which OpenCL version or NVidia driver version do you test for this library ?

**Comment by WincerChan** [comment]
@wngasinur The driver version should not be an issue. This is the GPU driver version I used:
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M.
